### ISSUE TITLE
MSYS2 instead of Cygwin

### ISSUE THREAD

**Issue by 44iCdnz** [TheRealMichaelWang/cish#53]
Cygwin's GCC creates dependency on cygwin-1.dll. MSYS2 with MINGW64 doesn't.

To compile on MSYS2 MINGW64, on Makefile of cish remove -ldl and on Makefile of Capote add -mconsole

Everything compiled fine, but cish is unable to compile any examples.

The error message:

```
$ cish -c -s fib.cish -o fib
in fib.cish: row 1, col 26
        ;
Syntax error(cannot open file).
```

The guide on release page said copy stdlib directory into either cish or Capote working directory. But I found this directory are already there on both directories. I overwrote it with my downloaded stdlib anyway. Doesn't work. The last resort, I copied stdlib directory into examples directory where fib.cish is placed. Still doesn't work!

I'm out of ideas.

**Comment by TheRealMichaelWang** [comment]
When you include a library from the standard library, you have to include the standard library directory (ie `include "stdlib/io.csh"`). Some of the examples are broken tho.

**Comment by 3oheicrw** [comment]
It's also fail with the same error on the MSYS2 GCC (which is essentially just a fork of Cygwin GCC, it's different from MINGW64 GCC).

**Comment by 3oheicrw** [comment]
@TheRealMichaelWang Your Makefiles are problematic. I tried compiling with this command: cd src && gcc -c *.c && gcc -o cish *.o and magically it worked. The same is true for Capote.

**Comment by 3oheicrw** [comment]
> @TheRealMichaelWang Your Makefiles are problematic. I tried compiling with this command: cd src && gcc -c *.c && gcc -o cish *.o and magically it worked. The same is true for Capote.
> 
> Update: it's with the MSYS2 GCC, not MINGW64 GCC.

Update: it's also work with the MINGW64 GCC. Please, @TheRealMichaelWang, fix your Makefiles.

**Comment by 3oheicrw** [comment]
Note: my comments are about building of cish and Capote themselves, not related to the OP's problems that his cish can't compile any examples.

**Comment by 44iCdnz** [comment]
> When you include a library from the standard library, you have to include the standard library directory (ie `include "stdlib/io.cish"`). Some of the examples are broken tho.

stdlib.zip still uses .csh extension. The included stdlib of cish uses .cish extension. But I followed your guide on release page so I overwrote the included stdlib with stdlib.zip. I should use the source on release page but not clone from github as this caused the mismatch. BTW, you should make the transition from .csh extension to .cish extension complete and make a new release.

**Comment by 44iCdnz** [comment]
@TheRealMichaelWang The new release should be based on MSYS2 MINGW64 though. Your code is very portable, you don't need Cygwin GCC. That's the whole point of this thread. Unable to compile examples is just a minor problem.

**Comment by Xanderplayz16** [comment]
This was fixed.

**Comment by 3oheicrw** [comment]
> This was fixed.

I don't think so. There is no new PRs, no new commits. This means there is no code change. This was not fixed.

**Comment by Xanderplayz16** [comment]
The stdlib.zip was fixed.

**Comment by Xanderplayz16** [comment]
Just download the new one for 1.1.1. I fixed it.
